#!/usr/bin/env python3
"""Generate the exact seven-seed PIS temperature posterity replay."""

from __future__ import annotations

import argparse
from copy import deepcopy
import hashlib
from pathlib import Path
from typing import Any

import yaml


RUN_ID = "f3950b2e"
SOURCE_RUN_ID = "5c7a10e2"
SCRIPT_DIR = Path(__file__).resolve().parent
SOURCE_CONFIG = SCRIPT_DIR / "experiments_qwen3_17b_l2r_temperature_mixture.yaml"
CELLS = ("PIS-T1", "PIS-TMIX1.2")
SEEDS = (1481, 1483, 1487, 1489, 1499, 1511, 1523)


def _sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def _source_payload() -> dict[str, Any]:
    payload = yaml.safe_load(SOURCE_CONFIG.read_text(encoding="utf-8"))
    if not isinstance(payload, dict):
        raise ValueError("temperature source configuration is not an object")
    return payload


def build_payload() -> dict[str, Any]:
    payload = deepcopy(_source_payload())
    payload["run_id"] = RUN_ID
    payload["defaults"]["out"] = (
        "~/po_results/2026-08-29/reproducibility/"
        "pis-temperature-mixture-posterity__f3950b2e"
    )
    diagnostic = payload["diagnostic"]
    diagnostic["stage"] = "exact_temperature_mixture_posterity_replay"
    diagnostic["evidence_class"] = "same_seed_current_code_reproducibility_replay"
    diagnostic["provenance"] = {
        "source_run_id": SOURCE_RUN_ID,
        "source_config": SOURCE_CONFIG.name,
        "source_config_sha256": _sha256(SOURCE_CONFIG),
        "selection_rule": "exact replay; no temperature selected from replay outcomes",
    }
    diagnostic["analysis_contract"] = [
        "Treat paired training seed as the independent replicate.",
        "Report Final Acc@1 first, strict final accuracy second and trajectory AUC third.",
        "Repeat the original prespecified paired contrasts without retuning temperature or mixture fraction.",
        "Treat differences from the source run as reproducibility measurements.",
        "Do not access the official GSM8K test split.",
    ]
    validate_payload(payload)
    return payload


def validate_payload(payload: dict[str, Any]) -> None:
    source = _source_payload()
    if payload.get("run_id") != RUN_ID:
        raise ValueError("temperature posterity run ID changed")
    if payload.get("tag_prefix") != source.get("tag_prefix"):
        raise ValueError("temperature tag prefix changed")
    if payload.get("algos") != source.get("algos"):
        raise ValueError("temperature scientific cells changed")
    defaults = deepcopy(payload.get("defaults") or {})
    defaults["out"] = source["defaults"]["out"]
    if defaults != source.get("defaults"):
        raise ValueError("temperature fixed defaults changed")
    diagnostic = payload.get("diagnostic") or {}
    design = diagnostic.get("design") or {}
    if tuple(design.get("cells") or ()) != CELLS:
        raise ValueError("temperature cells changed")
    if tuple(design.get("seed_values") or ()) != SEEDS:
        raise ValueError("temperature seeds changed")
    if design.get("array_tasks") != 14:
        raise ValueError("temperature task count changed")
    if (diagnostic.get("fixed_contract") or {}).get("official_test_used") is not False:
        raise ValueError("official-test prohibition is missing")


def render_payload() -> str:
    header = (
        "# Generated by generate_qwen3_17b_pis_temperature_posterity.py.\n"
        "# Edit the generator, regenerate this file, and run its --check mode.\n"
    )
    return header + yaml.safe_dump(
        build_payload(), sort_keys=False, width=100, allow_unicode=False
    )


def main() -> int:
    parser = argparse.ArgumentParser()
    group = parser.add_mutually_exclusive_group()
    group.add_argument("--check", type=Path, metavar="YAML")
    group.add_argument("--write", type=Path, metavar="YAML")
    args = parser.parse_args()
    expected = render_payload()
    if args.check is not None:
        actual = yaml.safe_load(args.check.read_text(encoding="utf-8"))
        if actual != build_payload():
            raise SystemExit(f"generated configuration drift: {args.check}")
        print(f"verified generated configuration: {args.check}")
        return 0
    if args.write is not None:
        args.write.write_text(expected, encoding="utf-8")
        print(f"wrote generated configuration: {args.write}")
        return 0
    print(expected, end="")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
